version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.35.0
    ports:
      - "9090:9090"
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  
  grafana:
   image: grafana/grafana-oss:8.5.2
   pull_policy: always
   ports: 
     - "3000:3000"
   container_name: grafana
   restart: unless-stopped
   volumes:
      - ./data/grafana:/var/lib/grafana
   environment: 
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost